buzz_pattern:
  target:
    entity:
      integration: ampio
      domain: siren
  fields:
    tone:
      required: true
      example: 6
      selector:
        number:
          min: 0
          max: 31
          mode: box
    seconds:
      required: true
      example: 0.3
      selector:
        number:
          min: 0
          max: 655.35
          step: 0.01
          unit_of_measurement: s
          mode: box
    tone2:
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 31
          mode: box
    seconds2:
      example: 0.3
      default: 0.0
      selector:
        number:
          min: 0
          max: 655.35
          step: 0.01
          unit_of_measurement: s
          mode: box
    cycles:
      example: 3
      default: 1
      selector:
        number:
          min: 0
          max: 254
          mode: box
    delay:
      example: 0
      default: 0.0
      selector:
        number:
          min: 0
          max: 655.35
          step: 0.01
          unit_of_measurement: s
          mode: box
lock_touch:
  target:
    entity:
      integration: ampio
      domain: button
  fields:
    seconds:
      required: true
      example: 30
      selector:
        number:
          min: 0.01
          max: 655.35
          step: 0.01
          unit_of_measurement: s
          mode: box
set_backlight_fields:
  target:
    entity:
      integration: ampio
      domain: light
  fields:
    fields:
      required: true
      example: "[1, 2]"
      selector:
        object:
    rgbw_color:
      required: true
      example: "[255, 100, 100, 50]"
      selector:
        object:
set_status_fields:
  target:
    entity:
      integration: ampio
      domain: light
  fields:
    fields:
      required: true
      example: "[1, 2]"
      selector:
        object:
    rgb_color:
      required: true
      example: "[255, 100, 100]"
      selector:
        color_rgb:
send_notification:
  fields:
    message:
      required: true
      example: Brama otwarta
      selector:
        text:
